name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, nuxt ]
  pull_request:
    branches: [ main, nuxt ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Nix Cache
        uses: cachix/cachix-action@v12
        with:
          name: devenv

      - name: Install dependencies
        run: |
          nix develop -c npm install

      - name: Build project
        env:
          NODE_ENV: production
        run: |
          nix develop -c npm run generate

      - name: Add .nojekyll file
        run: |
          touch dist/public/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/public'


  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/nuxt'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
